# Generated by Django 4.0 on 2021-12-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password2',
            field=models.CharField(max_length=50),
        ),
    ]
