# Generated by Django 4.0 on 2021-12-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(choices=[('R', 'Red'), ('B', 'Black'), ('P', 'Pink'), ('D', 'Default')], default='D', max_length=6),
        ),
        migrations.AddField(
            model_name='category',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('B', 'Both')], default='B', max_length=6),
        ),
        migrations.AddField(
            model_name='category',
            name='sport_type',
            field=models.CharField(choices=[('F', 'Football'), ('C', 'Creket'), ('B', 'Both')], default='B', max_length=6),
        ),
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
