# Generated by Django 4.0 on 2021-12-24 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category_color_category_gender_category_sport_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
