# Generated by Django 4.0 on 2022-03-29 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_image3_product_image4_product_image5'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image5',
        ),
    ]
