# Generated by Django 4.0 on 2021-12-22 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_customer_alter_order_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quntity',
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
