# Generated by Django 4.0 on 2021-12-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_quntity_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Padding'), ('OFD', 'Out For Delivery'), ('D', 'Delivered')], default='P', max_length=13),
        ),
    ]
