# Generated by Django 4.0 on 2021-12-23 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category_color_category_gender_category_sport_type_and_more'),
        ('orders', '0004_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='product.category'),
        ),
    ]
