# Generated by Django 4.0 on 2021-12-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_order_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(18, 'Padding'), (52, 'Out For Delivery'), (100, 'Delivered')], default=18, max_length=13),
        ),
    ]
