# Generated by Django 4.0 on 2021-12-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Padding'), ('OFD', 'Out For Delivery'), ('D', 'Delivered')], default='D', max_length=13),
        ),
    ]
